/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 05 14:17:53 GMT 2019
 */

package test.todo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import test.todo.Todo;
import test.todo.TodoController;
import test.todo.TodoService;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TodoController_ESTest extends TodoController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TodoService todoService0 = new TodoService();
      TodoController todoController0 = new TodoController(todoService0);
      List<Todo> list0 = todoController0.index();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TodoController todoController0 = new TodoController((TodoService) null);
      Todo todo0 = new Todo((Integer) null, "");
      // Undeclared exception!
      try { 
        todoController0.create(todo0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("test.todo.TodoController", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TodoController todoController0 = new TodoController((TodoService) null);
      // Undeclared exception!
      try { 
        todoController0.index();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("test.todo.TodoController", e);
      }
  }
}
